name: CI-CD

on:
  push:
    branches: [ develop, main, feature/*, hotfix/* ]
  pull_request:
    branches: [ develop, main ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Compile
        run: echo Hello, world!
      
      - name: Teste
        run: echo ${{github.ref}}

  Deploy_Homologation:
    name: Deploy to Homologation
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/develop'
    environment: 
      name: Development
      url: http://azure.dev.com
          
    steps:
      - name: Run a one-line script
        run: echo I am deploying to Homologation

  Deploy_Production:
    name: Deploy to Production    
    runs-on: ubuntu-latest
    needs: [Deploy_Homologation]
    if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'

    environment: 
      name: Production
      url: http://azure.com
      
    steps:
      - name: Run a one-line script
        run: echo I am deploying to Production
