name: CI-CD Multi-Server

on:
  push:
    branches: [ develop, main, feature/*, hotfix/* ]
  pull_request:
    branches: [ develop, main ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run a one-line script
        run: echo I am deploying to Homologation

  Artifact:
    name: Generate Artifact
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Run a one-line script
        run: echo I am generating the deploy package

  Deploy_RIGHTNOW01:
    name: Deploy to RIGHTNOW01
    runs-on: ubuntu-latest
    needs: [Artifact]
    if: github.ref == 'refs/heads/main'
    environment: 
      name: RIGHTNOW01
      url: http://127.0.0.1
          
    steps:
      - name: Run a one-line script
        run: echo I am deploying to RIGHTNOW01]

  Deploy_RIGHTNOW02:
    name: Deploy to RIGHTNOW02
    runs-on: ubuntu-latest
    needs: [Artifact]
    if: github.ref == 'refs/heads/main'
    environment: 
      name: RIGHTNOW02
      url: http://127.0.0.2
          
    steps:
      - name: Run a one-line script
        run: echo I am deploying to RIGHTNOW02
        
  Deploy_RIGHTNOW03:
    name: Deploy to RIGHTNOW03
    runs-on: ubuntu-latest
    needs: [Artifact]
    if: github.ref == 'refs/heads/main'
    environment: 
      name: RIGHTNOW03
      url: http://127.0.0.3
          
    steps:
      - name: Run a one-line script
        run: echo I am deploying to RIGHTNOW03
