name: Workflow Sync Main

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
      
  workflow_dispatch:

jobs:
  Syncronize:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run a one-line script
        run: echo I am sync 'main' to 'develop'
