name: Workflow CI

on:
  push:
    branches: [ develop, main, feature/*, hotfix/* ]
  pull_request:
    branches: [ develop, main ]

  workflow_dispatch:

jobs:
  APP1-BUILD:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo Build APP1

  APP2-BUILD:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo Build APP2
        
  APP3-BUILD:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo Build APP3

  GENERATE-VERSION:
    runs-on: ubuntu-latest
    needs: [APP1-BUILD, APP2-BUILD, APP3-BUILD]

    outputs:
      output1: ${{ steps.version.outputs.version_tag }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Check Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          major_pattern: "{MAJOR}"
          minor_pattern: "{MINOR}"
          format: "${major}.${minor}.${patch}"
          short_tags: false
          # If this is set to true, *every* commit will be treated as a new version.
          bump_each_commit: false
  
  CHECK-VERSION:
    name: ${{ needs.GENERATE-VERSION.outputs.output1 }}
    runs-on: ubuntu-latest
    needs: [GENERATE-VERSION]
      
    steps:
      - name : Version ${{ needs.GENERATE-VERSION.outputs.output1 }}
        run: echo ${{ needs.GENERATE-VERSION.outputs.output1 }}

